### PR TITLE
Clean params which was created when cleaning a Join to a Sub

### PR DESCRIPTION
**Pull request by azatoth**

### CODE REVIEW

**Comment by stilvoid** [comment]
Hey, if you can add a unit test to cover the case, I'll gladly merge this in :)

**Comment by azatoth** [comment]
@stilvoid I did update the examples which are used in the unit tests to show more complex examples, I hope that's enough

**Comment by azatoth** [comment]
@stilvoid I've added separate tests for the nested clean operator now instead, I decided to write it using pytest and also added a tox.ini  for testing it with both py27 and py36 plus coverage reporting.

**Comment by azatoth** [comment]
@stilvoid still with us mate? Would love to have this fix released so I don't have to force my colleagues to have to use my fork.

**Comment by stilvoid** [comment]
I've merged this with a couple of changes. I might bring tox in at a later date but I've just kept it simple for now.

**Pull request merged**
