### PR TITLE
Multibyte support

### PR DESCRIPTION
**Pull request by toriiico**
Hello, Thank you for a wonderful tool.

When using this tool to flip the template containing multibyte characters, garbled characters occurred.
And I fixed this.
The sample is json -> yaml, but yaml -> json is also supported.

Please let me know if there is any problem.

### Before
Sample file: examples/test_multibyte.json
```json
{
    "Description": "僕の名前は成田です。"
}
```
execute
```bash
$ fn-flip examples/test_multibyte.json examples/test_multibyte.json.yaml
```
result
```yaml
Description: "\u50D5\u306E\u540D\u524D\u306F\u6210\u7530\u3067\u3059\u3002"
```

### After
When multi-byte characters are included, it is modified to be supported by the -m or --multibyte option.

```
$ fn-flip -m examples/test_multibyte.json examples/test_multibyte.json.yaml
```
```yaml
Description: 僕の名前は成田です。
```

### Environment
- Python 2.7.15
- Python 3.6.7

### CODE REVIEW

**Comment by koiker** [comment]
We just need to fix the new test to run with Python 2.7, otherwise I think it's good.

**Comment by stilvoid** [comment]
Is there any reason to want this as a switchable option and not just enabled by default? I'd be happy that we just always have `allow_unicode=True` as it's 2019 :)

**Comment by toriiico** [comment]
@stilvoid 
> Is there any reason to want this as a switchable option and not just enabled by default? I'd be happy that we just always have `allow_unicode=True` as it's 2019 :)

I simply inverted because the default was False.
In other words, there is no deep intention;)
I do not have much confidence in the handling of character codes, but since I agree with that proposal, I will apply it!

**Comment by koiker** [comment]
I agree that we can add the multi-byte support as the default.
Can you change again the code to just use multi-byte?

**Comment by toriiico** [comment]
Sorry, I was misunderstanding...
I'll Update to always support multi-byte !

**Comment by stilvoid** [comment]
Love it! Thanks for the contribution :)

**Pull request merged**
