### PR TITLE
Use latest pytest release

### PR DESCRIPTION
**Pull request by michael-k**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by koiker** [comment]
Maybe we should change the pytest requirement to > (greater than) this will keep the package up-to-date (until some pytest change break the things :-P)

**Comment by michael-k** [comment]
I'd like that.  But then cron jobs should be used at travis ci to catch incompatibilities with newer versions of pytest early, see https://docs.travis-ci.com/user/cron-jobs/.  Otherwise tests for PRs would fail unrelated to the change, making life harder for contributors.

**Comment by michael-k** [comment]
@koiker In the meantime pytest 4.3.0 has been released.  Should I adjust the PR to use `pytest>=4.3.0` or `pytest<4.4`?
I cannot tell if your comment is meant as something that should be done or something you're thinking about.

**Comment by koiker** [comment]
Michael, change to ```pytest>=4.3.0```

**Comment by michael-k** [comment]
Done :)

**Pull request merged**
